### ISSUE TITLE
配置中参数代表的分别是什么？

### ISSUE THREAD

**Issue by qiuyunzhao** [dongfg/notify#1]
{
  "corpId": "YOUR CORP ID",
  "corpSecret": "APP SECRET",
  "agentId": APP AGENT ID
}
请问这几个分别对应什么呢？我在企业号新建的应用中只发现了这两个
 Secret、AgentId

**Comment by dongfg** [comment]
corpSecret，agentId 对应你新建应用的Secret、AgentId
corpId 在 我的企业 => 企业信息 最下的 企业ID
